import numpy as np
import pandas as pd

from projlib import config

HP = config.raw("entity").parents[2] / "Hoberg_Phillips_TNIC"
OUT = config.out("09_appendix/hp_validation", "x").parent
OUT.mkdir(parents=True, exist_ok=True)
Y0, Y1 = config.YEAR_MIN, config.YEAR_MAX
E = "FACTSET_ENTITY_ID"

cw = pd.read_parquet(config.out("02_gvkey_crosswalk", "crosswalk_entity_gvkey_year.parquet"), columns=[E, "fyear", "gvkey"]).dropna()
cw["gvkey"] = pd.to_numeric(cw["gvkey"], errors="coerce")
cw = cw.dropna().drop_duplicates([E, "fyear"]).astype({"gvkey": "int64"})
gk = cw.set_index([E, "fyear"])["gvkey"]
rp = pd.read_parquet(config.out("07_panel", "rival_pair_traits.parquet"), columns=["focal", "rival", "year", "mutual"])
rp = rp[rp["year"].between(Y0, Y1)].drop_duplicates(["focal", "rival", "year"]).copy()
rp["g1"] = gk.reindex(list(zip(rp["focal"], rp["year"]))).values
rp["g2"] = gk.reindex(list(zip(rp["rival"], rp["year"]))).values
ent = pd.read_parquet(config.out("01_universe", "entities.parquet"), columns=[E, "ISO_COUNTRY", "ENTITY_TYPE"]).drop_duplicates(E).set_index(E)
cov = pd.read_stata(config.raw("entity_coverage"), convert_categoricals=False, columns=[E, "PRIMARY_SIC_CODE"]).drop_duplicates(E)
sic = pd.to_numeric(cov.set_index(E)["PRIMARY_SIC_CODE"], errors="coerce")


def read_hp(name):
    x = pd.read_csv(HP / name, sep="\t", dtype={"year": "int32", "gvkey1": "int64", "gvkey2": "int64", "score": "float32"})
    return x[x["year"].between(Y0, Y1)]


hhi = pd.read_csv(HP / "TNIC3HHIdata.txt", sep="\t")
hhi = hhi[hhi["year"].between(Y0, Y1)]
lines = ["# Our rival relationships against Hoberg and Phillips's text-based network", "",
         f"Window {Y0}-{Y1}. Generated by `estimation/07_hoberg_phillips_validation.py`. Pairs: designated rival pair-years (the focal firm names the rival).", ""]
rows = []
UNIV = {}
for bench, fname in (("TNIC-3", "tnic3_data.txt"), ("ETNIC-3", "ETNIC3_data.txt")):
    hp = read_hp(fname)
    univ = set(zip(hhi["gvkey"], hhi["year"])) if bench == "TNIC-3" else set(zip(hp["gvkey1"], hp["year"])) | set(zip(hp["gvkey2"], hp["year"]))
    key = pd.Series(hp["score"].values, index=pd.MultiIndex.from_arrays([hp["year"].values, hp["gvkey1"].values, hp["gvkey2"].values]))
    key = key[~key.index.duplicated()]
    obs1 = np.array([(a, y) in univ for a, y in zip(rp["g1"].fillna(-1).astype("int64"), rp["year"])])
    obs2 = np.array([(a, y) in univ for a, y in zip(rp["g2"].fillna(-1).astype("int64"), rp["year"])])
    r = rp[obs1 & obs2].copy()
    r["score"] = key.reindex(list(zip(r["year"], r["g1"].astype("int64"), r["g2"].astype("int64")))).values
    r["in_hp"] = r["score"].notna()
    fy = rp[obs1][["focal", "year", "g1"]].drop_duplicates(["focal", "year"])
    fy["sic4"] = fy["focal"].map(sic); fy["sic3"] = fy["sic4"] // 10
    fy2 = fy.dropna(subset=["sic4"])
    rnd = fy2.groupby("year", group_keys=False).apply(lambda d: d.sample(min(len(d), 600), random_state=1))
    grp = fy2.groupby(["year", "sic3"], group_keys=False).apply(lambda d: d.sample(min(len(d), 150), random_state=1))
    sp = pd.concat([rnd.merge(rnd, on="year", suffixes=("", "_b")).assign(kind="random"),
                    grp.merge(grp, on=["year", "sic3"], suffixes=("", "_b")).assign(sic3_b=lambda d: d["sic3"], kind="same3")], ignore_index=True)
    sp = sp[sp["g1"] < sp["g1_b"]]
    sp["in_hp"] = key.reindex(list(zip(sp["year"], sp["g1"].astype("int64"), sp["g1_b"].astype("int64")))).notna().values | \
                  key.reindex(list(zip(sp["year"], sp["g1_b"].astype("int64"), sp["g1"].astype("int64")))).notna().values
    s3 = sp[sp["kind"].eq("same3")]
    b3 = s3["in_hp"].mean(); b4 = s3.loc[s3["sic4"].eq(s3["sic4_b"]), "in_hp"].mean(); b0 = sp.loc[sp["kind"].eq("random"), "in_hp"].mean()
    rows.append({"benchmark": bench, "named pair-years": len(rp), "observable in both": len(r), "share observable": len(r) / len(rp),
                 "named pairs in network": r["in_hp"].mean(), "one-way named in network": r.loc[r["mutual"].ne(1), "in_hp"].mean(),
                 "mutual in network": r.loc[r["mutual"].eq(1), "in_hp"].mean(), "same SIC4 pairs in network": b4, "same SIC3 pairs in network": b3,
                 "random pairs of our firms in network": b0, "score, named pairs (median)": r["score"].median()})
    named = set(zip(r["year"], r["g1"].astype("int64"), r["g2"].astype("int64")))
    fset = set(zip(fy["g1"].astype("int64"), fy["year"]))
    hq = hp[[(a, y) in fset for a, y in zip(hp["gvkey1"], hp["year"])]]
    hq = hq[[(b, y) in univ for b, y in zip(hq["gvkey2"], hq["year"])]]
    hq = hq.assign(named=[(y, a, b) in named for y, a, b in zip(hq["year"], hq["gvkey1"], hq["gvkey2"])])
    per = hq.groupby(["gvkey1", "year"]).agg(n_hp=("named", "size"), n_named=("named", "sum"))
    rows[-1].update({"network pairs of our firms named by them": hq["named"].mean(), "network rivals per firm-year (median)": per["n_hp"].median(),
                     "of which named (median)": per["n_named"].median(), "score, network pairs named (median)": hq.loc[hq["named"], "score"].median(),
                     "score, network pairs not named (median)": hq.loc[~hq["named"], "score"].median()})
    r.to_parquet(OUT / f"hp_named_pairs_{bench.replace('-', '').lower()}.parquet", index=False)
    UNIV[bench] = univ
    print(bench, "done")
t = pd.DataFrame(rows).set_index("benchmark").T
t.to_csv(OUT / "hp_agreement.csv")
lines += ["## Agreement and selectivity", "", t.to_markdown(floatfmt=".3f"), ""]

rp["rival_cty"] = rp["rival"].map(ent["ISO_COUNTRY"]); rp["focal_cty"] = rp["focal"].map(ent["ISO_COUNTRY"]); rp["rival_type"] = rp["rival"].map(ent["ENTITY_TYPE"])
tn = hhi.assign(k=list(zip(hhi["gvkey"], hhi["year"])))
tset = set(tn["k"])
rp["focal_in_tnic"] = [(a, y) in tset for a, y in zip(rp["g1"].fillna(-1).astype("int64"), rp["year"])]
rp["both_in_tnic"] = rp["focal_in_tnic"] & np.array([(a, y) in tset for a, y in zip(rp["g2"].fillna(-1).astype("int64"), rp["year"])])
ev = pd.read_parquet(config.out("07_panel", "exposure_events.parquet"), columns=["focal", "related", "kind", "cls", "year"])
ev = ev[ev["kind"].eq("rival") & ev["cls"].str.startswith("consolidation") & ev["year"].between(Y0, Y1)].drop_duplicates(["focal", "related", "year"])
ev["g1"] = gk.reindex(list(zip(ev["focal"], ev["year"]))).values; ev["g2"] = gk.reindex(list(zip(ev["related"], ev["year"]))).values
ev["both_in_tnic"] = [(a, y) in tset and (b, y) in tset for a, b, y in zip(ev["g1"].fillna(-1).astype("int64"), ev["g2"].fillna(-1).astype("int64"), ev["year"])]
ev["both_in_etnic"] = [(a, y) in UNIV["ETNIC-3"] and (b, y) in UNIV["ETNIC-3"] for a, b, y in zip(ev["g1"].fillna(-1).astype("int64"), ev["g2"].fillna(-1).astype("int64"), ev["year"])]
rp["both_in_etnic"] = [(a, y) in UNIV["ETNIC-3"] and (b, y) in UNIV["ETNIC-3"] for a, b, y in zip(rp["g1"].fillna(-1).astype("int64"), rp["g2"].fillna(-1).astype("int64"), rp["year"])]
c = {"both firms in the ETNIC-3 universe that year": rp["both_in_etnic"].mean(), "rival-deal pairs with both firms in ETNIC-3": ev["both_in_etnic"].mean(),
     "designated pair-years": len(rp), "focal firm outside the US": rp["focal_cty"].ne("US").mean(), "rival outside the US": rp["rival_cty"].ne("US").mean(),
     "rival private (FactSet entity type not PUB)": rp["rival_type"].ne("PUB").mean(), "one-way pairs (direction recorded)": rp["mutual"].ne(1).mean(),
     "both firms in the TNIC-3 universe that year": rp["both_in_tnic"].mean(), "rival-deal pairs (focal, consolidating rival, year)": len(ev),
     "rival-deal pairs with both firms in TNIC-3": ev["both_in_tnic"].mean()}
lines += ["## Coverage: what the text network cannot see", "", pd.Series(c).to_frame("value").to_markdown(floatfmt=".3f"), ""]
pd.Series(c).to_csv(OUT / "hp_coverage.csv")
(OUT / "hp_validation.md").write_text("\n".join(lines), encoding="utf-8")
print("\n".join(lines))
